M48
; DRILL file {KiCad 9.0.0} date 2025-03-08T20:05:44+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-08T20:05:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X168.0Y-77.5
X168.0Y-108.0
X198.3Y-77.45
X198.35Y-108.0
M30
